### ISSUE TITLE
Android purchase restore - from 0.2.1 to 0.3 - stop working

### ISSUE THREAD

**Issue by stefano-orlandini** [Wizcorp/cordova-plugin-wizpurchase#20]
hello 
I do not know if I am writing in the right place. 
I'm using this plugin and I have had some problems 
after being passed from version 0.2.1 to 0.3, the restore on Android has stopped working.
Always return empty array "[]".

in the function QueryInventoryFinishedListener when create return Object the "developerPayload" not exist in skuObject and cause exception.
I fix with this code:

if(skuObject.has("developerPayload")){
   pendingObject.putOpt("developerPayload", skuObject.getString("developerPayload"));
}else{
   pendingObject.putOpt("developerPayload", "");	
}

**Comment by alexbleks** [comment]
i have a problem with this in any version... buying it the first time works fine.

**Comment by aogilvie** [comment]
@jrouault this might still be relevant

**Comment by jrouault** [comment]
Fixed in #42
