### ISSUE TITLE
Android cannot consume unmanaged products

### ISSUE THREAD

**Issue by avivais** [Wizcorp/cordova-plugin-wizpurchase#23]
The error callback of ```consumePurchase``` is invoked with message:

```
Sku: ["XXXX"] was not consumable
```

Looks like ```mInventory.getPurchase(sku)``` is returning null even for owned products, though I do see them when I call ```getPending```

This also leads to the item cannot be purchased again (alreadyOwned error)

**Comment by avivais** [comment]
I identified the issue, easily reproduced. Perhaps I was passing an array instead of a single value, but this is now consolidated with the iOS plugin.

Fixed [here](https://github.com/avivais/phonegap-plugin-wizPurchase/commit/fb5c8e2ca3ba200cdba336c7c720d2db44a79759)
(Don't mind the typo, Fixed [here](https://github.com/avivais/phonegap-plugin-wizPurchase/commit/791f3ec415ccaa7c52c3735dbaf884f6e24b32c1)

Another thing worth mentioning is the lack of consumePurchase successcallback, added [here](https://github.com/avivais/phonegap-plugin-wizPurchase/commit/7b5b4881b2c3f9ef1efe1bfaf39d2abd4748a940)

**Comment by ronkorving** [comment]
But you're not supposed to pass an array, right?

**Comment by avivais** [comment]
I wanted to consolidate with the iOS version, where an array is expected...

**Comment by ronkorving** [comment]
@aogilvie ? feedback?

**Comment by jrouault** [comment]
This issue should have been fixed starting v2.0.0, please re-open the issue if you still encounter this problem.
