### ISSUE TITLE
Callbacks Not Fired on Android

### ISSUE THREAD

**Issue by jkassis** [Wizcorp/cordova-plugin-wizpurchase#45]
I've seen at least two errors... "not logged in" and "item not available" while testing my Android integration so far. These were admittedly on a debug build, but the plugin isn't firing the error callbacks at all. I'll try it as an alpha build now.

**Comment by jkassis** [comment]
haven't tested this yet using an alpha build (Google Play Store is slow!?!?!). However, I did initiate a test of a static response (see https://developer.android.com/google/play/billing/billing_testing.html). I initiated the "android.test.purchased" transaction and completed it with Google Play. But no callback. Not even a success callback.

**Comment by ronkorving** [comment]
Are you on the latest version of wizPurchase?

**Comment by jkassis** [comment]
testing this stuff is a pita! i'll update this when i know more.

**Comment by jkassis** [comment]
stale

**Comment by jkassis** [comment]
stale
