### ISSUE TITLE
Android - NPE on cancel purchase

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [Wizcorp/cordova-plugin-wizpurchase#49]
Hello!

I have found an NPE here are the logs:

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.smartmobilesoftware.util.Purchase.getSku()' on a null object reference
> at jp.wizcorp.wizpurchase.WizPurchase$10.onIabPurchaseFinished(WizPurchase.java:727)
> 

It happen when I start a purchase, and cancel it buy clicking outside de Google Play window.

File:
https://github.com/Wizcorp/cordova-plugin-wizpurchase/blob/master/src/android/WizPurchase.java#L727

I thought about make a PR with a
`if(purchase != null)`

But not sure if it's normal that purchase is null here...

Regards,

**Comment by ronkorving** [comment]
I think the problem is that the result is not being inspected before using product. If the result is a failure, product may be null. Going by Google's example [here](https://developer.android.com/training/in-app-billing/purchase-iab-products.html), we should first be checking the result.

Thoughts?
