### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by csicky** [Wizcorp/cordova-plugin-wizpurchase#52]
Hi, this should be asked on StackOverflow, I know, but I am not sure if I get answers there because Google did not find too many wizPurchase hits.

My problem is that nothing seems to happen. I tried to make purchase using debug version of the app and logged the results, hoping I get an error, but nothing. I created signed release version, uploaded to alpha channel, tested using test account, again nothing. Not dialog from Google Play asking for money, no error. I have a div in the page where I log json stringified logs, I use it when I don't have console, in release mode. I tried to write there the success and error responses from wizPurchase.getProductDetails, makePurchase, but nothing appears.

I will paste here some of my code, maybe you find the problem:

```javascript
import store from '../store'
var dispatch = store.dispatch

var StoreHolder = {}
;(function() {
  window.addEventListener('load', ev => {
    document.addEventListener(
      'deviceready',
      deviceready => {
        console.log('window in deviceready', window)
        init()
      },
      false
    )
  })
})()

function init() {
  dispatch('insertLog', { timeStamp: new Date(), info: 'init window.wizPurchase', details: window.wizPurchase })
  StoreHolder.wizPurchase = window.wizPurchase
}

export default StoreHolder
```

Then in my Vue.js app I check vor `wizPurchase` being present and only then I call its methods:

```javascript
    import StoreHolder from './modules/store'
    //...
    test(id) {
      this.insertLog({ timeStamp: new Date(), info: 'test call', details: StoreHolder })

      if (StoreHolder.wizPurchase) {
        this.insertLog({ timeStamp: new Date(), info: 'test wizPurchase', details: StoreHolder.wizPurchase })
        // I get to this place, StoreHolder.wizPurchase exists and it is logged

        //below code seems to be doing nothing at all, also no error
        StoreHolder.wizPurchase.getProductDetails(
          id,
          success => {
            this.insertLog({ timeStamp: new Date(), info: 'test call', details: success })
            console.log('success', success)
          },
          error => {
            this.insertLog({ timeStamp: new Date(), info: 'test call', details: error })
            console.log('error', error)
          }
        )
      }
    }
```

Thank you for your help!

**Comment by aogilvie** [comment]
What does adb logcat output? You might get more verbose output from CLI rather than Android Studio/Cordova CLI

**Comment by csicky** [comment]
```
03-25 08:48:39.038 11543-11582/com.fancsiki.dangerouslove D/WizPurchase: initialising plugin
03-25 08:48:39.038 11543-11582/com.fancsiki.dangerouslove W/System.err:     at jp.wizcorp.wizpurchase.WizPurchase.initialize(WizPurchase.java:119)
```
Which points to
```java
// Assign base64 encoded public key
int billingKey = cordova.getActivity().getResources().getIdentifier("billing_key", "string", cordova.getActivity().getPackageName());
mBase64EncodedPublicKey = cordova.getActivity().getString(billingKey);
```
It seems that it can't find the billing key? It's added inside config.xml:

```
    <plugin name="cordova-plugin-wizpurchase" spec="2.2.0">
        <variable name="BILLING_KEY" value="MIIBIjAN..." />
    </plugin>
```

Thank you for your time.

**Comment by csicky** [comment]
I've added the key as a hard-coded string and it seems to work.

```java
//line: 119
mBase64EncodedPublicKey = "MIIBIjA..."
```
If you could tell me how to fix it to take the key from config.xml would be super, but if not, I will leave it hardcoded.

**Comment by jrouault** [comment]
Hello, thanks for posting about your issue!
Could you provide more information so that we could try to reproduce the issue, such as:
- Cordova version (command `cordova -v`) 
- Cordova Android version (command `cordova platform ls` or `cordova platform version android`)
- Device and Android version

**Comment by csicky** [comment]
Here is the info:
`cordova version 8.0.0`

```
cordova platform version android

Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```
I am using for testing Galaxy S8 with Android version 8.0.0, kernel 4.4.13.

However, the problem seems to be with my project, for some reason the variable `BILLING_KEY` is not propagated to the Android code. I have added it when installing the plugin using `cordova plugin add https://github.com/Wizcorp/cordova-plugin-wizpurchase --variable BILLING_KEY="YOUR_BILLING_KEY"` and thyen I changed `spec="2.2.0"` in config.xml, it looks like this:
```xml
<plugin name="cordova-plugin-wizpurchase" spec="2.2.0">
    <variable name="BILLING_KEY" value="MIIBIjANBgkqh....." />
</plugin>
```

**Comment by jrouault** [comment]
My first guess was that it would come from some major changes how Cordova handles the configuration.

You could try to remove the `android` platform and re-add it as well.

We will have a look ASAP if we can reproduce it.

**Comment by csicky** [comment]
After removing and adding the android platform, running `cordova run android` I get error that InAppBillingService is missing and can't be imported.
```
cordova\platforms\android\app\src\main\java\com\smartmobilesoftware\util\IabHelper.java:32: error: package com.android.vending.billing does not exist
import com.android.vending.billing.IInAppBillingService;
```
I searched for `IInAppBillingService` inside android folder and I found it at path `\cordova\platforms\android\src\com\android\vending\billing\IInAppBillingService.aidl`.

A Google search pointed me to this fix for the above error, which says to take the file and place it in another folder `cordova\platforms\android\app\src\main\aidl\com\android\vending\billing\`
The place where I found the solution for the error: https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/196

After fixing that, I am back at square one, meaning it can't load the billing key from the config.xml file.
Logcat: `W/System.err:     at jp.wizcorp.wizpurchase.WizPurchase.initialize(WizPurchase.java:119)`

**Comment by jrouault** [comment]
Thanks for trying that out and pointing at this other issue.

We could reproduce your initial issue with Cordova 8 and Cordova Android 7.

It seems like Cordova Android 7 introduced some major changes related to project structure and config files. See: https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html
It should be possible to fix those two issues you mentioned by updating the `plugin.xml` file. However, it might break the compatibility with older versions of Cordova Android.

We will have a look at it but it might take a few days/weeks before we can't get back at you on this with the proper fix.

**Comment by csicky** [comment]
I think that this aidl file can live in both folders. Older versions will search for it in initial location and the new version will take it from the new one. But this is only part of the problem. I am not a Cordova expert, I work usually only on web. Thank you.

**Comment by stevecarlton** [comment]
@csicky You might try `cordova platform rm android` and then `cordova platform add android@6.4.0`

Not using this plugin yet but I have had several issues with plugins from the 7.0.0 version as it changed several things about the build process that broke many plugins.

**Comment by csicky** [comment]
@stevecarlton I am still working on other parts of the application, and since it is working with the billing key hard-coded inside the java file I can work with this as it is for now. By the time I need to publish to production I am sure everything will be resolved.

**Comment by jrouault** [comment]
Sorry for coming back at this so late.
PR #55 should fix your issue. It would be great if you could confirm that.
We will make a new major release with these changes if everything goes fine.

**Comment by csicky** [comment]
I don't have time now to check if it works. I work on a different project and I am very busy. If you could reproduce it and it is fixed now on your end it means it's ok. Thank you.
