### ISSUE TITLE
Question about Auto-Renewing Subscriptions

### ISSUE THREAD

**Issue by stevecarlton** [Wizcorp/cordova-plugin-wizpurchase#53]
Hello!

I am currently using the cordova-purchase-plugin but I am looking to implement auto-renewing subscriptions in my app which seems extremely complicated for some reason.

Does this plugin handle the receipt validation without the need of our own server? If it does not, is there something that is plug and play to handle validation? Ideally, I would love to just fire up a Heroku instance or something to handle it if I can.

How does this plugin handle expired subscriptions and how can I check for that? Didn't see this mentioned in the readme.

Thank you.

**Comment by jrouault** [comment]
Hello,

Sadly this plugin does not support subscription. It was not designed with subscription in mind. It would require quite some work to add this feature at this point and we didn't plan for it.
Therefore, I would not recommend this plugin if you need support for subscription.

As for receipt validation, this plugin doesn't support it locally. And I am not aware of any plug-and-play system that you could just fire up in Heroku.
We have a simple npm package (made by @ronkorving) to do IAP verification: https://www.npmjs.com/package/iap. However, this would probably require a minimum amount of back-end work before you could simply boot it in Heroku.

**Comment by stevecarlton** [comment]
@jrouault I appreciate the quick response and honest answer. I'll close my thread, have a great one and thanks!
